import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { assertSafeTransport, fetchCatalog, validateCatalog } from "../../packages/vibe-cli/catalog.mjs";
import { run } from "../../packages/vibe-cli/index.mjs";

const good = {
  catalog_version: "v1",
  graphs: {
    zeta: { labels: ["B", "A"], edges: [{ name: "REL", from: "B", to: "A" }] },
    alpha: { labels: ["A", "A"], edges: [] }
  }
};
const ok = body => async () => ({ ok: true, status: 200, async text() { return typeof body === "string" ? body : JSON.stringify(body); } });

test("validates and normalizes a v1 catalog deterministically", () => {
  const catalog = validateCatalog(good);
  assert.deepEqual(Object.keys(catalog.graphs), ["alpha", "zeta"]);
  assert.deepEqual(catalog.graphs.zeta.labels, ["A", "B"]);
  assert.deepEqual(catalog.graphs.alpha.labels, ["A"]);
});

test("rejects malformed, unsupported and hostile catalogs", () => {
  const bad = [
    null, [], "x", {},
    { catalog_version: "v2", graphs: {} },
    { catalog_version: "v1" },
    { catalog_version: "v1", graphs: { "bad name": { labels: [], edges: [] } } },
    { catalog_version: "v1", graphs: { g: { labels: ["Bad-Label"], edges: [] } } },
    { catalog_version: "v1", graphs: { g: { labels: ["A"], edges: [{ name: "E;DROP", from: "A", to: "A" }] } } },
    { catalog_version: "v1", graphs: { g: { labels: "A", edges: [] } } },
    JSON.parse('{"catalog_version":"v1","graphs":{"__proto__":{"labels":["A"],"edges":[]}}}'),
    JSON.parse('{"catalog_version":"v1","graphs":{"g":{"labels":["constructor"],"edges":[]}}}')
  ];
  for (const payload of bad) assert.throws(() => validateCatalog(payload), error => error.name === "CatalogError");
  assert.equal({}.polluted, undefined);
});

test("refuses to send bearer tokens over plain http to non-loopback hosts", () => {
  assertSafeTransport("https://api.example.com");
  assertSafeTransport("http://127.0.0.1:3000");
  assertSafeTransport("http://localhost:3000");
  assert.throws(() => assertSafeTransport("http://api.example.com"), e => e.code === "INSECURE_TRANSPORT");
  assert.throws(() => assertSafeTransport("ftp://api.example.com"), e => e.code === "INSECURE_TRANSPORT");
  assert.throws(() => assertSafeTransport("not a url"), e => e.code === "INVALID_BASE_URL");
});

test("fetchCatalog requires a token, validates the path, sends bearer auth and never echoes bodies", async () => {
  await assert.rejects(() => fetchCatalog({ baseUrl: "https://x", token: "", fetchImpl: ok(good) }), e => e.code === "MISSING_TOKEN");
  for (const catalogPath of ["rpc/x", "/../etc", "/a//b", "/a?b=c", true]) {
    await assert.rejects(() => fetchCatalog({ baseUrl: "https://x", token: "t", catalogPath, fetchImpl: ok(good) }), e => e.code === "INVALID_CATALOG_PATH", String(catalogPath));
  }
  let seen;
  const catalog = await fetchCatalog({ baseUrl: "https://x.example/", token: "tok", fetchImpl: async (url, init) => { seen = { url, init }; return ok(good)(); } });
  assert.equal(seen.url, "https://x.example/rpc/vibe_schema_catalog");
  assert.equal(seen.init.headers.authorization, "Bearer tok");
  assert.equal(seen.init.redirect, "error");
  assert.equal(Object.keys(catalog.graphs).length, 2);
  await assert.rejects(
    () => fetchCatalog({ baseUrl: "https://x", token: "tok", fetchImpl: async () => ({ ok: false, status: 401, async text() { return "secret-server-detail"; } }) }),
    e => e.code === "CATALOG_REQUEST_FAILED" && /401/.test(e.message) && !e.message.includes("secret-server-detail")
  );
  await assert.rejects(() => fetchCatalog({ baseUrl: "https://x", token: "tok", fetchImpl: ok("not json") }), e => e.code === "INVALID_CATALOG");
  await assert.rejects(() => fetchCatalog({ baseUrl: "https://x", token: "tok", fetchImpl: ok("x".repeat(2_000_001)) }), e => e.code === "INVALID_CATALOG");
});

test("vibe schema pull generates deterministic types from a validated remote catalog", async () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), "vibe-pull-"));
  const previous = { token: process.env.VIBE_TOKEN, base: process.env.VIBE_BASE_URL };
  process.env.VIBE_TOKEN = "tok";
  process.env.VIBE_BASE_URL = "https://api.example";
  try {
    const out = [];
    assert.equal(await run(["schema", "pull"], { cwd, fetchImpl: ok(good), stdout: v => out.push(v), stderr() {} }), 0);
    assert.equal(out.join(""), "// Generated by Vibe CLI from Schema Catalog.\nexport type VibeGraph = \"alpha\" | \"zeta\";\nexport type VibeLabel = \"A\" | \"B\";\n");
    assert.equal(await run(["schema", "pull", "--out", "vibe.d.ts", "--catalog-out", "catalog.json"], { cwd, fetchImpl: ok(good), stdout() {}, stderr() {} }), 0);
    assert.match(fs.readFileSync(path.join(cwd, "vibe.d.ts"), "utf8"), /VibeGraph/);
    assert.equal(JSON.parse(fs.readFileSync(path.join(cwd, "catalog.json"), "utf8")).catalog_version, "v1");
    assert.equal(fs.existsSync(path.join(cwd, ".vibe")), false);
    delete process.env.VIBE_TOKEN;
    await assert.rejects(() => run(["schema", "pull"], { cwd, fetchImpl: ok(good), stdout() {}, stderr() {} }), /VIBE_TOKEN is required/);
    process.env.VIBE_TOKEN = "tok";
    process.env.VIBE_BASE_URL = "http://api.example";
    await assert.rejects(() => run(["schema", "inspect"], { cwd, fetchImpl: ok(good), stdout() {}, stderr() {} }), /plain http/);
  } finally {
    for (const [key, value] of [["VIBE_TOKEN", previous.token], ["VIBE_BASE_URL", previous.base]]) if (value === undefined) delete process.env[key]; else process.env[key] = value;
  }
});
