import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {parseArgs,generateTypes,run} from "../../packages/vibe-cli/index.mjs";
import {listMigrationFiles} from "../../packages/vibe-cli/migrate.mjs";

test("parses repeated flags",()=>{const args=parseArgs(["graph","query","--graph","g","--eq","name=Alice","--eq","age=3"]);assert.deepEqual(args.eq,["name=Alice","age=3"]);});
test("generates deterministic catalog types",()=>{const catalog={graphs:{zeta:{labels:["B","A"]},alpha:{labels:["A","C"]}}};assert.equal(generateTypes(catalog),"// Generated by Leruchi CLI from Schema Catalog.\nexport type LeruchiGraph = \"alpha\" | \"zeta\";\nexport type LeruchiLabel = \"A\" | \"B\" | \"C\";\n");});
test("config never stores token",async()=>{const cwd=fs.mkdtempSync(path.join(os.tmpdir(),"vibe-cli-"));const output=[];const code=await run(["config","set","--base-url","https://api.example"],{cwd,stdout:v=>output.push(v),stderr:()=>{}});assert.equal(code,0);const config=JSON.parse(fs.readFileSync(path.join(cwd,".leruchi/config.json"),"utf8"));assert.deepEqual(config,{baseUrl:"https://api.example"});assert.equal(JSON.stringify(config).includes("token"),false);});
test("builds query through SDK rather than a second compiler",async()=>{const calls=[];const cwd=fs.mkdtempSync(path.join(os.tmpdir(),"vibe-cli-"));fs.mkdirSync(path.join(cwd,".vibe"));fs.writeFileSync(path.join(cwd,".vibe/config.json"),JSON.stringify({baseUrl:"https://api.example"}));const code=await run(["graph","query","--graph","g","--label","Account","--select","name","--eq","name=Alice"],{cwd,fetchImpl:async(url,init)=>{calls.push({url,init});return{ok:true,status:200,async json(){return{rows:[]}}};},stdout:()=>{},stderr:()=>{}});assert.equal(code,0);assert.equal(calls[0].url,"https://api.example/v1/graph/query");const body=JSON.parse(calls[0].init.body);assert.equal(body.ir.kind,"graph_query");assert.equal(body.ir.filters[0].op,"eq");assert.equal(body.ir.filters[0].value,"Alice");});
test("rejects unsafe identifiers through SDK boundary",async()=>{const cwd=fs.mkdtempSync(path.join(os.tmpdir(),"vibe-cli-"));fs.mkdirSync(path.join(cwd,".vibe"));fs.writeFileSync(path.join(cwd,".vibe/config.json"),JSON.stringify({baseUrl:"https://api.example"}));await assert.rejects(()=>run(["graph","query","--graph","g","--label","Account","--select","name;DROP"],{cwd,stdout:()=>{},stderr:()=>{}}),/Field must be a valid Leruchi field/);});

test("remote schema inspection uses authenticated catalog endpoint",async()=>{
  const cwd=fs.mkdtempSync(path.join(os.tmpdir(),"vibe-cli-"));
  fs.mkdirSync(path.join(cwd,".vibe"));
  fs.writeFileSync(path.join(cwd,".vibe/config.json"),JSON.stringify({baseUrl:"https://api.example"}));
  const calls=[];
  const output=[];
  process.env.LERUCHI_TOKEN="test-token";
  try {
    const code=await run(["schema","inspect"],{cwd,fetchImpl:async(url,init)=>{
      calls.push({url,init});
      return {ok:true,status:200,async json(){return {version:"v1",graphs:{demo:{labels:["Account"],edges:[]}}}}};
    },stdout:v=>output.push(v),stderr:()=>{}});
    assert.equal(code,0);
    assert.equal(calls[0].url,"https://api.example/v1/schema/catalog");
    assert.equal(calls[0].init.headers.authorization,"Bearer test-token");
    assert.match(output[0],/demo/);
  } finally { delete process.env.LERUCHI_TOKEN; }
});

test("migration command refuses non-migrator connection URLs",async()=>{
  const cwd=fs.mkdtempSync(path.join(os.tmpdir(),"vibe-cli-"));
  process.env.VIBE_MIGRATOR_DATABASE_URL="postgresql://vibe_runtime:runtime@localhost:5432/leruchi";
  try {
    await assert.rejects(()=>run(["db","migrate"],{cwd,stdout:()=>{},stderr:()=>{}}),/vibe_migrator/);
  } finally { delete process.env.VIBE_MIGRATOR_DATABASE_URL; }
});

test("discovers numbered migrations deterministically",()=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),"vibe-migrations-"));
  for(const name of ["0001-z.sql","0000-migration-ledger.sql","README.md","9999_BAD.sql","0002-next.sql"]) fs.writeFileSync(path.join(dir,name),"");
  assert.deepEqual(listMigrationFiles(dir).map(x=>x.id),["0000-migration-ledger","0001-z","0002-next"]);
});


test("retrieval command uses the SDK unified retrieval endpoint",async()=>{
  const cwd=fs.mkdtempSync(path.join(os.tmpdir(),"vibe-cli-retrieval-"));
  fs.mkdirSync(path.join(cwd,".vibe"));
  fs.writeFileSync(path.join(cwd,".vibe/config.json"),JSON.stringify({baseUrl:"https://api.example"}));
  const graphIr={version:"v1",kind:"graph_query",graph:"g",root:{label:"Account",alias:"n"},steps:[],filters:[],projection:[{field:"n.id",alias:"id"}],orderBy:[],limit:10,offset:0,depth:0,parameters:[]};
  const graphFile=path.join(cwd,"graph.json");
  fs.writeFileSync(graphFile,JSON.stringify(graphIr));
  const calls=[];
  const code=await run(["retrieval","query","--graph-ir","graph.json","--vector-catalog-ref","docs.embedding","--embedding","[1,0,0]","--top-k","5","--max-results","5"],{
    cwd,fetchImpl:async(url,init)=>{calls.push({url,init});return{ok:true,status:200,async json(){return{rows:[]}}};},stdout:()=>{},stderr:()=>{}
  });
  assert.equal(code,0);
  assert.equal(calls[0].url,"https://api.example/v1/retrieval/query");
  const body=JSON.parse(calls[0].init.body);
  assert.equal(body.ir.kind,"retrieval_query");
  assert.equal(body.ir.sources.graph.query.kind,"graph_query");
  assert.equal(body.ir.sources.vector.catalog_ref,"docs.embedding");
  assert.deepEqual(body.parameters.embedding,[1,0,0]);
});

test("retrieval CLI fails before transport when vector embedding is missing",async()=>{
  const cwd=fs.mkdtempSync(path.join(os.tmpdir(),"vibe-cli-retrieval-"));
  fs.mkdirSync(path.join(cwd,".vibe"));
  fs.writeFileSync(path.join(cwd,".vibe/config.json"),JSON.stringify({baseUrl:"https://api.example"}));
  await assert.rejects(()=>run(["retrieval","query","--vector-catalog-ref","docs.embedding"],{cwd,fetchImpl:async()=>{throw new Error("transport should not run")},stdout:()=>{},stderr:()=>{}}),/Missing --embedding/);
});


test("CLI retrieval explain sends canonical IR without raw parameters",async()=>{
  const {run}=await import("../../packages/vibe-cli/index.mjs");
  const fs=await import("node:fs");
  const os=await import("node:os");
  const path=await import("node:path");
  const cwd=fs.mkdtempSync(path.join(os.tmpdir(),"vibe-stage24-"));
  fs.writeFileSync(path.join(cwd,"retrieval.json"),JSON.stringify({
    version:"v1",kind:"retrieval_query",
    sources:{vector:{catalog_ref:"documents.embedding",query_parameter:"embedding",top_k:2,identity_field:"id"}},
    fusion:{strategy:"weighted_rrf"},limits:{max_results:2,max_cost:20}
  }));
  const seen=[];
  await run(["retrieval","explain","--base-url","http://127.0.0.1","--ir","retrieval.json"],{
    cwd,fetchImpl:async(url,options)=>{seen.push({url,body:JSON.parse(options.body)});return new Response(JSON.stringify({status:"ready",mode:"vector"}),{status:200,headers:{"content-type":"application/json"}})},
    stdout:()=>{},stderr:()=>{}
  });
  assert.equal(seen[0].url,"http://127.0.0.1/v1/retrieval/explain");
  assert.deepEqual(Object.keys(seen[0].body),["ir"]);
});


test("CLI Agent Intent explain validates and uses the SDK transport route",async()=>{
  const cwd=fs.mkdtempSync(path.join(os.tmpdir(),"vibe-agent-intent-"));
  fs.mkdirSync(path.join(cwd,".vibe"));
  fs.writeFileSync(path.join(cwd,".vibe/config.json"),JSON.stringify({baseUrl:"https://api.example"}));
  const query={version:"v1",kind:"graph_query",graph:"g",root:{label:"Person",alias:"root"},steps:[],filters:[],projection:[{field:"root.name",alias:"name"}],orderBy:[],limit:5,offset:0,depth:0,parameters:[]};
  fs.writeFileSync(path.join(cwd,"intent.json"),JSON.stringify({version:"v1",kind:"agent_intent",action:"query",ir:query}));
  const calls=[];
  const code=await run(["agent","intent","explain","--intent","intent.json"],{cwd,fetchImpl:async(url,init)=>{calls.push({url,body:JSON.parse(init.body)});return new Response(JSON.stringify({status:"ready"}),{status:200,headers:{"content-type":"application/json"}})},stdout:()=>{},stderr:()=>{}});
  assert.equal(code,0);
  assert.equal(calls[0].url,"https://api.example/v1/agent/intent/explain");
  assert.equal(calls[0].body.intent.kind,"agent_intent");
});

test("CLI Agent Intent rejects action/IR mismatch before transport",async()=>{
  const cwd=fs.mkdtempSync(path.join(os.tmpdir(),"vibe-agent-intent-"));
  fs.mkdirSync(path.join(cwd,".vibe"));
  fs.writeFileSync(path.join(cwd,".vibe/config.json"),JSON.stringify({baseUrl:"https://api.example"}));
  fs.writeFileSync(path.join(cwd,"intent.json"),JSON.stringify({version:"v1",kind:"agent_intent",action:"retrieval",ir:{version:"v1",kind:"graph_query"}}));
  let calls=0;
  await assert.rejects(()=>run(["agent","intent","explain","--intent","intent.json"],{cwd,fetchImpl:async()=>{calls++;throw new Error("transport should not run")},stdout:()=>{},stderr:()=>{}}),/does not match target IR kind/);
  assert.equal(calls,0);
});
