import assert from "node:assert/strict";
import test from "node:test";
import {createExecutionContext} from "../../packages/execution-context/index.mjs";
import {validateCrossModalPlan,explainCrossModalPlan,hashCrossModalPlan} from "../../packages/cross-modal-planner/index.mjs";

const catalog={graphs:{g:{visibility:"shared",labels:["Person"],edges:[]}}};
const query={version:"v1",kind:"graph_query",graph:"g",root:{label:"Person",alias:"root"},steps:[],filters:[],projection:[{field:"root.name",alias:"name"}],orderBy:[],limit:5,offset:0,depth:0,parameters:[]};
const retrieval={version:"v1",kind:"retrieval_query",sources:{graph:{query,identity_field:"id"}},fusion:{strategy:"weighted_rrf"},limits:{max_results:5,max_cost:10}};
const context={version:"v1",kind:"context_request",purpose:"bounded context",sources:[{type:"query",ir:query}],budget:{max_items:5,max_bytes:4096},freshness:{mode:"current"}};
const trusted=createExecutionContext({tenant_id:"t1",capabilities:["graph:read"]});

test("accepts query→retrieval→context dependency DAG",()=>{const plan={version:"v1",kind:"cross_modal_plan",steps:[{id:"q",type:"query",ir:query},{id:"r",type:"retrieval",ir:retrieval,depends_on:["q"]},{id:"c",type:"context",ir:context,depends_on:["r"]}]};const result=explainCrossModalPlan({plan,context:trusted,catalog});assert.equal(result.status,"ready");assert.deepEqual(result.step_order,["q","r","c"]);assert.equal(result.execution,"not_executed");});
test("rejects cycles",()=>{const plan={version:"v1",kind:"cross_modal_plan",steps:[{id:"a",type:"query",ir:query,depends_on:["b"]},{id:"b",type:"query",ir:query,depends_on:["a"]}]};assert.throws(()=>validateCrossModalPlan(plan),e=>e.code==="PLAN_CYCLE");});
test("rejects unknown dependencies",()=>{assert.throws(()=>validateCrossModalPlan({version:"v1",kind:"cross_modal_plan",steps:[{id:"q",type:"query",ir:query,depends_on:["missing"]}]}),e=>e.code==="PLAN_UNKNOWN_DEPENDENCY");});
test("derives union capabilities before execution",()=>{const vector={version:"v1",kind:"retrieval_query",sources:{vector:{catalog_ref:"docs.embedding",query_parameter:"embedding",top_k:2,identity_field:"id"}},fusion:{strategy:"weighted_rrf"},limits:{max_results:2,max_cost:10}};const result=explainCrossModalPlan({plan:{version:"v1",kind:"cross_modal_plan",steps:[{id:"r",type:"retrieval",ir:vector}]},context:trusted,catalog});assert.equal(result.status,"rejected");assert.equal(result.reason_code,"PLAN_CAPABILITY_DENIED");assert.deepEqual(result.missing_capabilities,["vector:read"]);});
test("rejects tenant and credential injection",()=>{assert.throws(()=>validateCrossModalPlan({version:"v1",kind:"cross_modal_plan",steps:[{id:"q",type:"query",tenant_id:"other",ir:query}]}),e=>e.code==="PLAN_TRUST_BOUNDARY_VIOLATION");});
test("mutation is represented as destructive but never executed",()=>{const mutation={version:"v1",kind:"graph_mutation",graph:"g",operation:"delete_vertex",target:{label:"Person",field:"id",value:"p1"},parameters:[]};const ctx=createExecutionContext({tenant_id:"t1",capabilities:["graph:write","graph:delete"]});const result=explainCrossModalPlan({plan:{version:"v1",kind:"cross_modal_plan",steps:[{id:"m",type:"mutation",ir:mutation}]},context:ctx,catalog});assert.equal(result.status,"ready");assert.equal(result.destructive,true);assert.equal(result.approval_required,true);assert.equal(result.execution,"not_executed");});
test("hash is deterministic",()=>{const plan={version:"v1",kind:"cross_modal_plan",steps:[{id:"q",type:"query",ir:query}]};assert.equal(hashCrossModalPlan(plan),hashCrossModalPlan(JSON.parse(JSON.stringify(plan))));});
test("observability excludes target IR and tenant",()=>{const logs=[];const plan={version:"v1",kind:"cross_modal_plan",steps:[{id:"q",type:"query",ir:query}]};explainCrossModalPlan({plan,context:trusted,catalog,observability:{emitLog:e=>logs.push(e)}});const s=JSON.stringify(logs);assert.equal(s.includes("tenant"),false);assert.equal(s.includes("graph_query"),false);});
