import fs from "node:fs";
import path from "node:path";
import {execFile} from "node:child_process";
import {promisify} from "node:util";
import {createClient} from "../vibe-sdk/index.mjs";
import {runMigrations} from "./migrate.mjs";
import {validateAgentIntent} from "../agent-intent/index.mjs";

const execFileAsync=promisify(execFile);
const CONFIG_DIR=".vibe";
const CONFIG_FILE="config.json";

export function parseArgs(argv) {
  const args={_:[]};
  for(let i=0;i<argv.length;i++){
    const token=argv[i];
    if(!token.startsWith("--")){args._.push(token);continue;}
    const raw=token.slice(2);
    const eq=raw.indexOf("=");
    if(eq>=0){const k=raw.slice(0,eq);const v=raw.slice(eq+1);args[k]=args[k]===undefined?v:Array.isArray(args[k])?[...args[k],v]:[args[k],v];continue;}
    const k=raw;
    const next=argv[i+1];
    if(next!==undefined&&!next.startsWith("--")){args[k]=args[k]===undefined?next:Array.isArray(args[k])?[...args[k],next]:[args[k],next];i++;}else args[k]=true;
  }
  return args;
}

function valuesOf(value){if(value===undefined||value===null)return [];return Array.isArray(value)?value:[value];}
function required(args,key){if(typeof args[key]!=="string"||args[key]==="")throw new Error(`Missing --${key}`);return args[key];}
function splitAssignment(value,name){const i=value.indexOf("=");if(i<=0)throw new Error(`${name} must use key=value`);return [value.slice(0,i),value.slice(i+1)];}
function parseJson(value,name){try{return JSON.parse(value);}catch{throw new Error(`${name} must be valid JSON`);}}
function parseProperties(values){
  const out={};
  for(const value of valuesOf(values)){const [key,val]=splitAssignment(value,"--property");if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key))throw new Error("Invalid property name");out[key]=val;}
  return out;
}
function loadConfig(cwd){
  const file=path.join(cwd,CONFIG_DIR,CONFIG_FILE);
  if(!fs.existsSync(file))return {};
  const parsed=JSON.parse(fs.readFileSync(file,"utf8"));
  if(!parsed||typeof parsed!=="object")throw new Error("Invalid .vibe/config.json");
  return parsed;
}
function saveConfig(cwd,config){
  const dir=path.join(cwd,CONFIG_DIR);
  fs.mkdirSync(dir,{recursive:true});
  fs.writeFileSync(path.join(dir,CONFIG_FILE),JSON.stringify(config,null,2)+"\n",{mode:0o600});
}
function clientOptions(cwd,args,fetchImpl){
  const config=loadConfig(cwd);
  const baseUrl=args["base-url"]||process.env.VIBE_BASE_URL||config.baseUrl;
  const token=process.env.VIBE_TOKEN;
  if(!baseUrl)throw new Error("VIBE_BASE_URL or .vibe/config.json baseUrl is required");
  return {baseUrl,token,fetchImpl};
}
function print(value,pretty=false){return JSON.stringify(value,null,pretty?2:0);}

export function generateTypes(catalog){
  const graphs=Object.keys(catalog?.graphs??{}).sort();
  const labels=[...new Set(graphs.flatMap(g=>catalog.graphs[g]?.labels??[]))].sort();
  return [
    "// Generated by Leruchi CLI from Schema Catalog.",
    "export type LeruchiGraph = "+(graphs.length?graphs.map(JSON.stringify).join(" | "):"never")+";",
    "export type LeruchiLabel = "+(labels.length?labels.map(JSON.stringify).join(" | "):"never")+";",
    "export type VibeGraph = LeruchiGraph;",
    "export type VibeLabel = LeruchiLabel;",
    ""
  ].join("\n");
}

export async function run(argv,{cwd=process.cwd(),fetchImpl=globalThis.fetch,stdout=console.log,stderr=console.error,exec=execFileAsync}={}) {
  const args=parseArgs(argv);
  const [command,subcommand,...rest]=args._;
  if(command==="config"){
    if(subcommand==="set"){
      const baseUrl=required(args,"base-url").replace(/\/$/,"");
      const config={...loadConfig(cwd),baseUrl};
      saveConfig(cwd,config);
      stdout(print({baseUrl:config.baseUrl,token:"environment-only"},true));return 0;
    }
    if(subcommand==="show"){
      const config=loadConfig(cwd);
      stdout(print({baseUrl:process.env.VIBE_BASE_URL||config.baseUrl||null,token:process.env.VIBE_TOKEN?"configured":"not configured"},true));return 0;
    }
    throw new Error("Usage: leruchi config set|show");
  }
  if(command==="db"&&subcommand==="migrate"){
    const result=await runMigrations({cwd});
    stdout(print(result,Boolean(args.pretty)));return 0;
  }
  if(command==="schema"&&(subcommand==="inspect"||subcommand==="types")){
    const baseUrl=(args["base-url"]||process.env.VIBE_BASE_URL||loadConfig(cwd).baseUrl||"").replace(/\/$/,"");
    if(!baseUrl)throw new Error("VIBE_BASE_URL or .vibe/config.json baseUrl is required");
    let catalog;
    if(args.remote||subcommand==="inspect"){
      if(!process.env.VIBE_TOKEN)throw new Error("VIBE_TOKEN is required for remote Schema Catalog inspection");
      const response=await fetchImpl(baseUrl+"/v1/schema/catalog",{headers:{authorization:`Bearer ${process.env.VIBE_TOKEN}`}});
      const payload=await response.json();
      if(!response.ok)throw new Error(payload?.error?.message||`Schema Catalog failed with HTTP ${response.status}`);
      catalog=payload;
    } else {
      const file=required(args,"file");
      catalog=JSON.parse(fs.readFileSync(path.resolve(cwd,file),"utf8"));
    }
    if(subcommand==="inspect"){stdout(print(catalog,Boolean(args.pretty)));return 0;}
    const generated=generateTypes(catalog);
    if(args.out){fs.writeFileSync(path.resolve(cwd,args.out),generated);stdout(`Wrote ${args.out}`);}else stdout(generated);
    return 0;
  }
  if(command==="local"&&subcommand==="status"){
    const {stdout:out}=await exec("docker",["compose","ps"],{cwd});
    stdout(out.trim());return 0;
  }
  if(command==="diagnostics"){
    const baseUrl=(args["base-url"]||process.env.VIBE_BASE_URL||loadConfig(cwd).baseUrl||"").replace(/\/$/,"");
    if(!baseUrl)throw new Error("VIBE_BASE_URL or .vibe/config.json baseUrl is required");
    const response=await fetchImpl(baseUrl+"/health",{headers:process.env.VIBE_TOKEN?{authorization:`Bearer ${process.env.VIBE_TOKEN}`}:{}});
    const payload=await response.text();
    if(!response.ok)throw new Error(`Diagnostics failed with HTTP ${response.status}`);
    stdout(payload);return 0;
  }
  if(command==="agent"&&subcommand==="plan"&&rest[0]==="explain"){
    const client=createClient(clientOptions(cwd,args,fetchImpl));
    const file=required(args,"plan");
    const plan=parseJson(fs.readFileSync(path.resolve(cwd,file),"utf8"),"--plan");
    const result=await client.request("cross-modal-plan-explain",{plan});
    stdout(print(result,Boolean(args.pretty)));return 0;
  }
  if(command==="agent"&&subcommand==="trace"){
    const client=createClient(clientOptions(cwd,args,fetchImpl));
    const file=required(args,"input");
    const input=parseJson(fs.readFileSync(path.resolve(cwd,file),"utf8"),"--input");
    const result=await client.request("agent-trace",input);
    stdout(print(result,Boolean(args.pretty)));return 0;
  }
  if(command==="agent"&&subcommand===("re"+"play")){
    const client=createClient(clientOptions(cwd,args,fetchImpl));
    const file=required(args,"trace");
    const trace=parseJson(fs.readFileSync(path.resolve(cwd,file),"utf8"),"--trace");
    const result=await client.request("agent-"+("re"+"play"),{trace});
    stdout(print(result,Boolean(args.pretty)));return 0;
  }
  if(command==="agent"&&subcommand==="evaluate"){
    const client=createClient(clientOptions(cwd,args,fetchImpl));
    const file=required(args,"cases");
    const cases=parseJson(fs.readFileSync(path.resolve(cwd,file),"utf8"),"--cases");
    if(!Array.isArray(cases)||!cases.length)throw new Error("--cases must contain a non-empty JSON array");
    const result=await client.request("agent-evaluate",{cases});
    stdout(print(result,Boolean(args.pretty)));return 0;
  }
  if(command==="agent"&&subcommand==="intent"&&rest[0]==="explain"){
    const client=createClient(clientOptions(cwd,args,fetchImpl));
    const file=required(args,"intent");
    const intent=parseJson(fs.readFileSync(path.resolve(cwd,file),"utf8"),"--intent");
    validateAgentIntent(intent);
    const result=await client.request("agent-intent-explain",{intent});
    stdout(print(result,Boolean(args.pretty)));return 0;
  }
  if(command==="retrieval"&&subcommand==="explain"){
    const client=createClient(clientOptions(cwd,args,fetchImpl));
    const file=required(args,"ir");
    const ir=parseJson(fs.readFileSync(path.resolve(cwd,file),"utf8"),"--ir");
    const result=await client.request("retrieval-explain",{ir});
    stdout(print(result,Boolean(args.pretty)));return 0;
  }
  if(command==="retrieval"&&subcommand==="query"){
    const client=createClient(clientOptions(cwd,args,fetchImpl));
    const builder=client.retrieval();
    if(args["graph-ir"]){
      const graphIr=parseJson(fs.readFileSync(path.resolve(cwd,required(args,"graph-ir")),"utf8"),"--graph-ir");
      builder.graph(graphIr,{identityField:args["graph-identity"]||"id",candidateLimit:args["candidate-limit"]?Number(args["candidate-limit"]):undefined});
    }
    if(args["vector-catalog-ref"]){
      builder.vector({
        catalogRef:required(args,"vector-catalog-ref"),
        queryParameter:args["vector-param"]||"embedding",
        topK:args["top-k"]?Number(args["top-k"]):10,
        identityField:args["vector-identity"]||"id"
      });
      const parameter=args["vector-param"]||"embedding";
      if(args.embedding===undefined)throw new Error("Missing --embedding for vector retrieval");
      builder.bind(parameter,"vector",parseJson(args.embedding,"--embedding"));
    }
    if(args["vector-weight"]!==undefined||args["graph-weight"]!==undefined){
      builder.fusion({vectorWeight:args["vector-weight"]===undefined?1:Number(args["vector-weight"]),graphWeight:args["graph-weight"]===undefined?1:Number(args["graph-weight"])});
    }
    if(args["max-results"]!==undefined||args["max-cost"]!==undefined){
      builder.limits({maxResults:args["max-results"]===undefined?20:Number(args["max-results"]),maxCost:args["max-cost"]===undefined?40:Number(args["max-cost"])});
    }
    const result=await builder.execute();
    stdout(print(result,Boolean(args.pretty)));return 0;
  }
  if(command==="graph"){
    const client=createClient(clientOptions(cwd,args,fetchImpl));
    const graph=required(args,"graph");
    if(subcommand==="query"){
      const query=client.graph(graph).query(required(args,"label"));
      const selects=valuesOf(required(args,"select")).flatMap(v=>v.split(",")).filter(Boolean);
      query.select(selects);
      for(const item of valuesOf(args.eq)){const [field,value]=splitAssignment(item,"--eq");query.eq(field,value);}
      if(args.limit)query.limit(Number(args.limit));
      if(args.offset)query.offset(Number(args.offset));
      if(args.depth)query.depth(Number(args.depth));
      const result=await query.execute();
      stdout(print(result,Boolean(args.pretty)));return 0;
    }
    if(subcommand==="create-vertex"){
      const result=await client.graph(graph).createVertex(required(args,"label"),parseProperties(args.property)).execute();
      stdout(print(result,Boolean(args.pretty)));return 0;
    }
    if(subcommand==="create-edge"){
      const result=await client.graph(graph).createEdge(
        required(args,"edge"),
        {label:required(args,"from-label"),field:required(args,"from-field"),value:required(args,"from-value")},
        {label:required(args,"to-label"),field:required(args,"to-field"),value:required(args,"to-value")},
        parseProperties(args.property)
      ).execute();
      stdout(print(result,Boolean(args.pretty)));return 0;
    }
    if(subcommand==="update-vertex"){
      const result=await client.graph(graph).updateVertex(required(args,"label"),required(args,"field"),required(args,"value")).properties(parseProperties(args.property)).execute();
      stdout(print(result,Boolean(args.pretty)));return 0;
    }
    if(subcommand==="delete-vertex"){
      const result=await client.graph(graph).deleteVertex(required(args,"label"),required(args,"field"),required(args,"value")).execute();
      stdout(print(result,Boolean(args.pretty)));return 0;
    }
    throw new Error("Usage: leruchi graph query|create-vertex|create-edge|update-vertex|delete-vertex");
  }
  throw new Error("Unknown command");
}

export async function main(argv=process.argv.slice(2),io={}) {
  try{return await run(argv,io);}catch(error){io.stderr?.(error.message);return 1;}
}
