import fs from "node:fs";
import path from "node:path";
import {execFile} from "node:child_process";
import {promisify} from "node:util";
import {createClient} from "../vibe-sdk/index.mjs";
import {MigrationError,connectMigrator,migrationStatus,runMigrations,scaffoldMigration,verifyMigrations,redact} from "./migrations.mjs";
import {DEFAULT_CATALOG_PATH,fetchCatalog} from "./catalog.mjs";

const execFileAsync=promisify(execFile);
const CONFIG_DIR=".vibe";
const CONFIG_FILE="config.json";

export function parseArgs(argv) {
  const args={_:[]};
  for(let i=0;i<argv.length;i++){
    const token=argv[i];
    if(!token.startsWith("--")){args._.push(token);continue;}
    const raw=token.slice(2);
    const eq=raw.indexOf("=");
    if(eq>=0){const k=raw.slice(0,eq);const v=raw.slice(eq+1);args[k]=args[k]===undefined?v:Array.isArray(args[k])?[...args[k],v]:[args[k],v];continue;}
    const k=raw;
    const next=argv[i+1];
    if(next!==undefined&&!next.startsWith("--")){args[k]=args[k]===undefined?next:Array.isArray(args[k])?[...args[k],next]:[args[k],next];i++;}else args[k]=true;
  }
  return args;
}

function valuesOf(value){if(value===undefined||value===null)return [];return Array.isArray(value)?value:[value];}
function required(args,key){if(typeof args[key]!=="string"||args[key]==="")throw new Error(`Missing --${key}`);return args[key];}
function splitAssignment(value,name){const i=value.indexOf("=");if(i<=0)throw new Error(`${name} must use key=value`);return [value.slice(0,i),value.slice(i+1)];}
function parseProperties(values){
  const out={};
  for(const value of valuesOf(values)){const [key,val]=splitAssignment(value,"--property");if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key))throw new Error("Invalid property name");out[key]=val;}
  return out;
}
function loadConfig(cwd){
  const file=path.join(cwd,CONFIG_DIR,CONFIG_FILE);
  if(!fs.existsSync(file))return {};
  const parsed=JSON.parse(fs.readFileSync(file,"utf8"));
  if(!parsed||typeof parsed!=="object")throw new Error("Invalid .vibe/config.json");
  return parsed;
}
function saveConfig(cwd,config){
  const dir=path.join(cwd,CONFIG_DIR);
  fs.mkdirSync(dir,{recursive:true});
  fs.writeFileSync(path.join(dir,CONFIG_FILE),JSON.stringify(config,null,2)+"\n",{mode:0o600});
}
function clientOptions(cwd,args,fetchImpl){
  const config=loadConfig(cwd);
  const baseUrl=args["base-url"]||process.env.VIBE_BASE_URL||config.baseUrl;
  const token=process.env.VIBE_TOKEN;
  if(!baseUrl)throw new Error("VIBE_BASE_URL or .vibe/config.json baseUrl is required");
  return {baseUrl,token,fetchImpl};
}
function print(value,pretty=false){return JSON.stringify(value,null,pretty?2:0);}

export function generateTypes(catalog){
  const graphs=Object.keys(catalog?.graphs??{}).sort();
  const labels=[...new Set(graphs.flatMap(g=>catalog.graphs[g]?.labels??[]))].sort();
  return [
    "// Generated by Vibe CLI from Schema Catalog.",
    "export type VibeGraph = "+(graphs.length?graphs.map(JSON.stringify).join(" | "):"never")+";",
    "export type VibeLabel = "+(labels.length?labels.map(JSON.stringify).join(" | "):"never")+";",
    ""
  ].join("\n");
}

function resolveMigrationsDir(cwd,dir){
  if(dir!==undefined&&(typeof dir!=="string"||dir===""))throw new Error("--dir requires a path");
  const resolved=path.resolve(cwd,dir??"migrations");
  const relative=path.relative(cwd,resolved);
  if(relative===""||relative.startsWith("..")||path.isAbsolute(relative))throw new Error("--dir must be a directory inside the project");
  return resolved;
}

function resolveBaseUrl(cwd,args){
  const baseUrl=(args["base-url"]||process.env.VIBE_BASE_URL||loadConfig(cwd).baseUrl||"").replace(/\/$/,"");
  if(!baseUrl)throw new Error("VIBE_BASE_URL or .vibe/config.json baseUrl is required");
  return baseUrl;
}

export async function run(argv,{cwd=process.cwd(),fetchImpl=globalThis.fetch,stdout=console.log,stderr=console.error,exec=execFileAsync,connect=connectMigrator}={}) {
  const args=parseArgs(argv);
  const [command,subcommand,...rest]=args._;
  if(command==="config"){
    if(subcommand==="set"){
      const baseUrl=required(args,"base-url").replace(/\/$/,"");
      const config={...loadConfig(cwd),baseUrl};
      saveConfig(cwd,config);
      stdout(print({baseUrl:config.baseUrl,token:"environment-only"},true));return 0;
    }
    if(subcommand==="show"){
      const config=loadConfig(cwd);
      stdout(print({baseUrl:process.env.VIBE_BASE_URL||config.baseUrl||null,token:process.env.VIBE_TOKEN?"configured":"not configured"},true));return 0;
    }
    throw new Error("Usage: vibe config set|show");
  }
  if(command==="schema"&&subcommand==="types"){
    const file=required(args,"file");
    const catalog=JSON.parse(fs.readFileSync(path.resolve(cwd,file),"utf8"));
    const generated=generateTypes(catalog);
    if(args.out){fs.writeFileSync(path.resolve(cwd,args.out),generated);stdout(`Wrote ${args.out}`);}else stdout(generated);
    return 0;
  }
  if(command==="schema"&&(subcommand==="inspect"||subcommand==="pull")){
    const catalog=await fetchCatalog({baseUrl:resolveBaseUrl(cwd,args),token:process.env.VIBE_TOKEN,catalogPath:args["catalog-path"]===undefined?DEFAULT_CATALOG_PATH:args["catalog-path"],fetchImpl});
    if(subcommand==="inspect"){stdout(print(catalog,true));return 0;}
    if(args["catalog-out"])fs.writeFileSync(path.resolve(cwd,args["catalog-out"]),print(catalog,true)+"\n");
    const generated=generateTypes(catalog);
    if(args.out){fs.writeFileSync(path.resolve(cwd,args.out),generated);stdout(`Wrote ${args.out}`);}else stdout(generated);
    return 0;
  }
  if(command==="migrate"){
    const dir=resolveMigrationsDir(cwd,args.dir);
    if(subcommand==="new"){
      const name=rest[0]||args.name;
      if(typeof name!=="string")throw new Error("Usage: vibe migrate new <name>");
      stdout(print({created:path.join(path.relative(cwd,dir),scaffoldMigration(dir,name))},true));return 0;
    }
    if(!["status","verify","up"].includes(subcommand))throw new Error("Usage: vibe migrate new|status|verify|up [--dry-run]");
    const url=process.env.VIBE_MIGRATOR_URL;
    if(!url)throw new Error("VIBE_MIGRATOR_URL is required (migrator role connection string; it is never stored in project configuration)");
    const client=await connect(url);
    try{
      let result;
      if(subcommand==="status")result=await migrationStatus(client,{dir});
      else if(subcommand==="verify")result=await verifyMigrations(client,{dir});
      else result=await runMigrations(client,{dir,dryRun:Boolean(args["dry-run"])});
      stdout(print(result,true));return 0;
    }catch(error){
      if(error instanceof MigrationError)throw error;
      throw new MigrationError("MIGRATION_FAILED",redact(error.message,url));
    }finally{
      try{await client.end();}catch{/* connection already closed */}
    }
  }
  if(command==="local"&&subcommand==="status"){
    const {stdout:out}=await exec("docker",["compose","ps"],{cwd});
    stdout(out.trim());return 0;
  }
  if(command==="diagnostics"){
    const baseUrl=(args["base-url"]||process.env.VIBE_BASE_URL||loadConfig(cwd).baseUrl||"").replace(/\/$/,"");
    if(!baseUrl)throw new Error("VIBE_BASE_URL or .vibe/config.json baseUrl is required");
    const response=await fetchImpl(baseUrl+"/health",{headers:process.env.VIBE_TOKEN?{authorization:`Bearer ${process.env.VIBE_TOKEN}`}:{}});
    const payload=await response.text();
    if(!response.ok)throw new Error(`Diagnostics failed with HTTP ${response.status}`);
    stdout(payload);return 0;
  }
  if(command==="graph"){
    const client=createClient(clientOptions(cwd,args,fetchImpl));
    const graph=required(args,"graph");
    if(subcommand==="query"){
      const query=client.graph(graph).query(required(args,"label"));
      const selects=valuesOf(required(args,"select")).flatMap(v=>v.split(",")).filter(Boolean);
      query.select(selects);
      for(const item of valuesOf(args.eq)){const [field,value]=splitAssignment(item,"--eq");query.eq(field,value);}
      if(args.limit)query.limit(Number(args.limit));
      if(args.offset)query.offset(Number(args.offset));
      if(args.depth)query.depth(Number(args.depth));
      const result=await query.execute();
      stdout(print(result,Boolean(args.pretty)));return 0;
    }
    if(subcommand==="create-vertex"){
      const result=await client.graph(graph).createVertex(required(args,"label"),parseProperties(args.property)).execute();
      stdout(print(result,Boolean(args.pretty)));return 0;
    }
    if(subcommand==="create-edge"){
      const result=await client.graph(graph).createEdge(
        required(args,"edge"),
        {label:required(args,"from-label"),field:required(args,"from-field"),value:required(args,"from-value")},
        {label:required(args,"to-label"),field:required(args,"to-field"),value:required(args,"to-value")},
        parseProperties(args.property)
      ).execute();
      stdout(print(result,Boolean(args.pretty)));return 0;
    }
    if(subcommand==="update-vertex"){
      const result=await client.graph(graph).updateVertex(required(args,"label"),required(args,"field"),required(args,"value")).properties(parseProperties(args.property)).execute();
      stdout(print(result,Boolean(args.pretty)));return 0;
    }
    if(subcommand==="delete-vertex"){
      const result=await client.graph(graph).deleteVertex(required(args,"label"),required(args,"field"),required(args,"value")).execute();
      stdout(print(result,Boolean(args.pretty)));return 0;
    }
    throw new Error("Usage: vibe graph query|create-vertex|create-edge|update-vertex|delete-vertex");
  }
  throw new Error("Unknown command");
}

export async function main(argv=process.argv.slice(2),io={}) {
  try{return await run(argv,io);}catch(error){(io.stderr??console.error)(error.message);return 1;}
}
